service: cart-api-natallia-a

plugins:
  - serverless-offline

useDotenv: true

provider:
  name: aws
  stage: 'dev'
  runtime: nodejs14.x
  region: 'eu-central-1'
  vpc:
    securityGroupIds:
      - 'sg-02046ca8c1f7f5d46'
      - 'sg-02046ca8c1f7f5d46'
    subnetIds:
      - 'subnet-7d955331'
      - 'subnet-0417926e'
      - 'subnet-cb5aaab7'
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
  iam: 
    role: 
      permissionsBoundary: 'arn:aws:iam::${aws:accountId}:policy/eo_role_boundary'
  profile: 'js-cc4-auto'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
